## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:           gst-thumbnailers
Version:        1.1.0
Release:        %autorelease
Summary:        GStreamer Thumbnailers

%gnome_check_version

SourceLicense:  GPL-3.0-or-later
# Rust dependencies:
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception
# BSD-3-Clause OR Apache-2.0
# GPL-3.0-or-later
# MIT
# MIT OR Apache-2.0
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT
License:        %{shrink:
    GPL-3.0-or-later
    AND Apache-2.0 WITH LLVM-exception
    AND MIT
    AND (Apache-2.0 OR MIT)
    AND (BSD-3-Clause OR Apache-2.0)
    AND (Unlicense OR MIT)
    AND (Zlib OR Apache-2.0 OR MIT)
}
# LICENSE.dependencies contains a full license breakdown

URL:            https://gitlab.gnome.org/GNOME/gst-thumbnailers
Source:         https://download.gnome.org/sources/%{name}/%{gnome_major_minor_version}/%{name}-%{gnome_tarball_version}.tar.xz

Patch:          0001-meson-adapt-for-RPM-package-build-environment.patch
Patch:          0002-cargo-drop-benchmarks-and-benchmark-only-dependencie.patch
Patch:          0003-Bump-libglycin-rebind-to-0.2.0-beta-for-GNOME-51.bet.patch

BuildRequires:  cargo-rpm-macros
BuildRequires:  meson >= 1.2

BuildRequires:  pkgconfig(glycin-2) >= 2.0.0
BuildRequires:  pkgconfig(gstreamer-1.0) >= 1.26.0

# GStreamer plugin dependencies (tests)
BuildRequires:  gstreamer1-plugins-base
BuildRequires:  gstreamer1-plugins-good

# GStreamer plugin dependencies (runtime)
Requires:       gstreamer1-plugins-base
Requires:       gstreamer1-plugins-good

%description
%{summary}.

%prep
%autosetup -n gst-thumbnailers-%{gnome_tarball_version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%meson
%meson_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%meson_install

%check
%ifnarch s390x
# https://gitlab.gnome.org/GNOME/gst-thumbnailers/-/issues/17
%meson_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%doc NEWS
%{_bindir}/gst-audio-thumbnailer
%{_bindir}/gst-video-thumbnailer
%dir %{_datadir}/thumbnailers
%{_datadir}/thumbnailers/gst-audio-thumbnailer.thumbnailer
%{_datadir}/thumbnailers/gst-video-thumbnailer.thumbnailer

%changelog
## START: Generated by rpmautospec
* Tue Sep 01 2026 Fabio Valentini <decathorpe@gmail.com> - 1.1.0-1
- Update to version 1.1.0; Fixes RHBZ#2526797

* Wed Aug 12 2026 Fabio Valentini <decathorpe@gmail.com> - 1.1~alpha-3
- Bump libglycin-rebind to 0.2.0-beta for GNOME 51.beta

* Thu Jul 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 1.1~alpha-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_45_Mass_Rebuild

* Thu Jul 02 2026 Fabio Valentini <decathorpe@gmail.com> - 1.1~alpha-1
- Update to version 1.1.alpha

* Fri Mar 13 2026 Fabio Valentini <decathorpe@gmail.com> - 1.0.0-1
- Update to version 1.0.0; Fixes RHBZ#2447346

* Wed Mar 11 2026 Fabio Valentini <decathorpe@gmail.com> - 1.0~rc-1
- Update to version 1.0.rc

* Fri Jan 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 1.0~alpha.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Thu Dec 11 2025 Fabio Valentini <decathorpe@gmail.com> - 1.0~alpha.1-1
- Initial import (#2420488)
## END: Generated by rpmautospec
